#!/bin/bash

echo ""
echo "Applying migration IndividualAlreadyRegistered"

echo "Adding routes to conf/app.routes"
echo "" >> ../conf/app.routes
echo "GET        /individualAlreadyRegistered                       controllers.IndividualAlreadyRegisteredController.onPageLoad()" >> ../conf/app.routes

echo "Adding messages to conf.messages"
echo "" >> ../conf/messages.en
echo "individualAlreadyRegistered.title = individualAlreadyRegistered" >> ../conf/messages.en
echo "individualAlreadyRegistered.heading = individualAlreadyRegistered" >> ../conf/messages.en

echo "Migration IndividualAlreadyRegistered completed"
